export const qna = {
  // --- Misinformation & Deception ---
  "False information spread unintentionally is called?": "misinformation",
  "False information spread intentionally to mislead is called?": "disinformation",
  "A completely fabricated story presented as news is a?": "hoax",
  "Sensationalist headlines designed for clicks are called?": "clickbait",
  "AI-generated, hyper-realistic fake videos are known as?": "deepfakes",
  "The fraudulent attempt to get sensitive info via email is called?": "phishing",
  "Using humor and exaggeration to critique society is called?": "satire",
  "A fake grassroots movement sponsored by an organization is called?": "astroturfing",
  "An advertisement designed to look like editorial content is called?": "native",
  "A story that is only partially true is often called?": "half-truth",
  "The spread of false information like a virus is described as going?": "viral",
  "A source that has been confirmed as trustworthy is considered?": "verified",
  "Information that lacks any factual basis is?": "unfounded",
  "A deliberately misleading or vague statement is an act of?": "obfuscation",

  // --- Bias & Perspective ---
  "The tendency to favor information confirming your beliefs is what kind of bias?": "confirmation",
  "An online space where you only see beliefs similar to your own is an?": "echochamber",
  "Algorithmic personalization that isolates you from different views creates a filter what?": "bubble",
  "Presenting information to influence how an audience interprets it is called?": "framing",
  "Unconscious stereotypes that affect our actions are what kind of bias?": "implicit",
  "Favoring one side of an issue is known as?": "bias",
  "Judging another culture by the standards of your own is called?": "ethnocentrism",
  "A firsthand account or original data is what kind of source?": "primary",
  "A source that analyzes or interprets original data is what kind of source?": "secondary",
  "The side of a story that is often unheard or ignored is the?": "counter-narrative",
  "The practice of verifying info by checking multiple sources is what kind of reading?": "lateral",
  "A viewpoint that is limited and doesn't consider the full picture is called?": "narrow",

  // --- Digital Citizenship & Online Behavior ---
  "The trail of data you leave online is your digital what?": "footprint",
  "Bullying that takes place over digital devices is called?": "cyberbullying",
  "Publicly revealing someone's private information online is called?": "doxing",
  "People who deliberately post inflammatory content online are called?": "trolls",
  "A modern form of social ostracism is often called what 'culture'?": "cancel",
  "The gap in tech access between different groups is the digital what?": "divide",
  "The principle of equal data treatment by internet providers is net what?": "neutrality",
  "Low-effort online support for a cause is often called?": "slacktivism",
  "Excessive admiration for an online personality can lead to what culture?": "stan",
  "The difficulty in making decisions due to too much information is called?": "overload",
  "A security process requiring two verification methods is called two-factor what?": "authentication",
  "Software designed to harm your computer is called?": "malware",
  "Unsolicited and unwanted digital communication is commonly known as?": "spam",
  "A person who breaks into computer systems is a?": "hacker",

  // --- Propaganda & Persuasion ---
  "Persuading people by claiming 'everyone is doing it' is the?": "bandwagon",
  "Using negative labels to create an unfavorable opinion is?": "name-calling",
  "Using vague, emotionally appealing words is glittering what?": "generalities",
  "An appeal to emotion is also known by its Greek name?": "pathos",
  "An appeal to credibility or ethics is known as?": "ethos",
  "An appeal to logic and reason is known as?": "logos",
  "Presenting only the information positive to an idea is card what?": "stacking",
  "A speaker presenting themselves as an 'average Joe' uses what appeal?": "plain-folks",
  "Projecting the qualities of one thing onto another is the technique of?": "transfer",
  "An endorsement from a respected figure is a?": "testimonial",
  "Information used to promote a biased political cause is called?": "propaganda",
  "The art of effective or persuasive speaking or writing is?": "rhetoric",

  // --- Social Awareness & Identity ---
  "An oversimplified image or idea of a particular group is a?": "stereotype",
  "The interconnected nature of social identities is called?": "intersectionality",
  "A person from a dominant group who advocates for an oppressed group is an?": "ally",
  "Prejudice against individuals with darker skin tones is called?": "colorism",
  "Discrimination against people with disabilities is called?": "ableism",
  "Discrimination based on a person's age is called?": "ageism",
  "The inappropriate adoption of a minority culture's customs is cultural?": "appropriation",
  "Giving everyone the same thing is?": "equality",
  "Giving people what they need to be successful is?": "equity",
  "A symbolic effort to include a member of a minority group is called?": "tokenism",
  "Subtle, everyday insults directed at marginalized groups are called?": "microaggressions",
  "Racism embedded as normal practice within a society is called?": "systemic",
  "Advantages held by a person based on their social identity group is?": "privilege",
  "A group of people with a shared culture, ancestry, or language is an?": "ethnicity",
  "The range of human differences is called?": "diversity",
  "The practice of creating environments for everyone is called?": "inclusion",
  "Prejudice directed at someone's sex or gender is?": "sexism",

  // --- Justice & Systemic Issues ---
  "Fairness in the way people are treated is called?": "justice",
  "The process of a wealthier class displacing residents in a neighborhood is?": "gentrification",
  "An invisible barrier preventing advancement for women and minorities is a glass what?": "ceiling",
  "A form of psychological manipulation making someone question their sanity is called?": "gaslighting",
  "A place where people can feel free from discrimination is a safe what?": "space",
  "Deceptively marketing a product as environmentally friendly is called?": "greenwashing",
  "A clear, voluntary, and enthusiastic agreement to an activity is?": "consent",
  "Policies that push students from schools into the justice system create a 'pipeline' to where?": "prison",
  "The fair distribution of environmental benefits and burdens is climate what?": "justice",
  "The state of being without reliable access to affordable, nutritious food is food what?": "insecurity",
  "Negative attitudes towards people with mental health conditions is called?": "stigma",

  // --- Media & Legal Concepts ---
  "The legal right granted to the creator of an original work is a?": "copyright",
  "Works to which no intellectual property rights apply are in the public what?": "domain",
  "Passing off someone else's work as your own is?": "plagiarism",
  "A license allowing free distribution of copyrighted work is Creative what?": "commons",
  "Permitted use of copyrighted material for criticism is what kind of 'use'?": "fair",
  "The concentration of media ownership in the hands of a few corporations is?": "consolidation",
  "An article that presents an author's personal viewpoint is an?": "opinion",
  "A person who collects and reports news is a?": "journalist",
  "The main body of law that deals with non-criminal disputes is what kind of law?": "civil",
  "A published false statement that is damaging to a person's reputation is?": "libel",
  "The group of people that a media piece is trying to reach is its target what?": "audience",
  "The different means of communication, like radio, TV, and internet, are the?": "media",
};